### PR TITLE
Allow installation as a Python package

### PR DESCRIPTION
**Pull request by swinkels**
Hello Charles,

The current version of git-cc is installed by copying it to a directory in your path or explicitly mention the path to gitcc when you execute it. In my Pull Request, I added the functionality to install git-cc as a proper Python package. This allows you to call gitcc from anywhere, to easily deinstall it later and to do without the "python gitcc" in vanilla Windows.

To do so, I had to add a setup.py file and support dynamic loading of the users.py module from a user-specified path. You can find the details changes in the PR. 

Note that I want to do some final integration testing of the changes but I can only do that at work - you know, ClearCase :) But this gives you the opportunity to have a first look and for me to get some feedback. 

Kind regards,

Pieter.

### CODE REVIEW

**Comment by charleso** [comment]
Hey Pieter.

Wow, that looks like a huge improvement. A test and everything!

Regarding the users.py, I'm wondering why I didn't just make it part of the `.git/gitcc` config rather than a python file (sheer laziness I'm sure). Not sure if that makes any of your changes easier?

Did you want to make any more changes or should I merge as-is?

**Comment by swinkels** [comment]
Hi Charles,

Thanks for the kind words!

About users.py, I thought about using a config file for the settings in this module. But that would have broken backwards compatibility, which I would like to avoid for now. With this PR, users only have to add a config setting and they can reuse their current users.py. Another benefit of leaving these settings in a Python module is that the required changes are minor.

There is one change I thought of after I made the PR: there is still an unused users.py that is installed together with the other modules. I want to remove that file.

Furthermore, I want to do some final testing at the office. Not that I expect an issue will pop up, but hey, it is not the first time I have been unpleasantly surprised :) I will let you know Monday evening CET, if it is good to go.

Kind regards,

Pieter.

**Comment by swinkels** [comment]
I tested the changes related to users.py (with an actual ClearCase instance) and everything works. I made one final change: I deleted git_cc/users.py as it has become a file that the user should provide. To have a nice history, I merged that deletion with an existing commit and hence the changes after our previous conversation.

So, please feel free to merge the PR!

**Comment by swinkels** [comment]
Hi @charleso, just a ping to inform you that the PR is ready for merge. Please let me know if it is not OK.

**Comment by charleso** [comment]
@swinkels Sorry for the delay, has been a crazy week. Thanks again for the PR! :)

**Comment by swinkels** [comment]
No problem. Thanks for merging!

Now git-cc is installable as a Python package, it also needs a version number. I am preparing a Pull Request for that - it is a bit more than just putting a number in setup.py - but at what number would you like to start? At 1.0.0?

**Comment by charleso** [comment]
I really don't mind, 1.0.0 makes as much sense as anything.

Sigh, I hate checking in version numbers, should just be based on a git tag. :(

**Comment by swinkels** [comment]
You know [zest.releaser](http://zestreleaser.readthedocs.io/en/latest/index.html)? It fully automates releases and that is what the PR will use. Of course you are free to discard the upcoming PR.

**Pull request merged**
